### PR TITLE
Move text_registrations and timers from WidgetState to Context State

### PR DESCRIPTION
**Pull request by Maan2003**
These just felt like global state. No idea why these were widget local earlier.

### CODE REVIEW

**Review by xarvic — APPROVED** [review]
Thanks!

**Comment by sjoshid** [comment]
This breaks `sub_window` example. Hover on the text for tooltip second time and you'll get
```
Sep 29 16:51:31.659 ERROR druid::window: No widget found for timer TimerToken(1)
thread 'main' panicked at 'supplied instant is later than self', library\std\src\time.rs:281:48
```
_PS: Im on Windows_

**Comment by Maan2003** [comment]
can't reproduce on gtk or x11 backends :/ . @sjoshid please attach a backtrace

**Comment by sjoshid** [comment]
Here you go
```
Sep 30 16:40:24.323 ERROR druid::window: No widget found for timer TimerToken(1)
thread 'main' panicked at 'supplied instant is later than self', library\std\src\time.rs:281:48
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\panicking.rs:515
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\core\src\panicking.rs:92
   2: core::option::expect_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\core\src\option.rs:1578
   3: core::option::Option::expect
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\core\src\option.rs:685
   4: std::time::Instant::duration_since
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\time.rs:281
   5: std::time::impl$5::sub
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\time.rs:407
   6: sub_window::impl$1::event<sub_window::HelloState,druid::widget::label::Label<sub_window::HelloState> >
             at .\druid\examples\sub_window.rs:119
   7: druid::widget::controller::impl$1::event<sub_window::HelloState,druid::widget::label::Label<sub_window::HelloState>,sub_window::TooltipController>
             at .\druid\src\widget\controller.rs:112
   8: druid::core::WidgetPod<sub_window::HelloState,druid::widget::controller::ControllerHost<druid::widget::label::Label<sub_window::HelloState>,sub_window::TooltipController> >::event<sub_window::HelloState,druid::widget::controller::ControllerHost<druid::wid
             at .\druid\src\core.rs:847
   9: druid::widget::env_scope::impl$1::event<sub_window::HelloState,druid::widget::controller::ControllerHost<druid::widget::label::Label<sub_window::HelloState>,sub_window::TooltipController> >
             at .\druid\src\widget\env_scope.rs:67
  10: druid::widget::widget::impl$1::event<sub_window::HelloState>
             at .\druid\src\widget\widget.rs:264
  11: druid::core::WidgetPod<sub_window::HelloState,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<sub_window::HelloState> >,alloc::alloc::Global> >::event<sub_window::HelloState,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<sub_window::HelloState>
             at .\druid\src\core.rs:847
  12: druid::widget::flex::impl$3::event<sub_window::HelloState>
             at .\druid\src\widget\flex.rs:632
  13: druid::widget::widget::impl$1::event<sub_window::HelloState>
             at .\druid\src\widget\widget.rs:264
  14: druid::core::WidgetPod<sub_window::HelloState,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<sub_window::HelloState> >,alloc::alloc::Global> >::event<sub_window::HelloState,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<sub_window::HelloState>
             at .\druid\src\core.rs:847
  15: druid::widget::align::impl$1::event<sub_window::HelloState>
             at .\druid\src\widget\align.rs:84
  16: druid::widget::widget::impl$1::event<sub_window::HelloState>
             at .\druid\src\widget\widget.rs:264
  17: druid::core::WidgetPod<sub_window::HelloState,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<sub_window::HelloState> >,alloc::alloc::Global> >::event<sub_window::HelloState,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<sub_window::HelloState>
             at .\druid\src\core.rs:847
  18: druid::window::Window<sub_window::HelloState>::event<sub_window::HelloState>
             at .\druid\src\window.rs:290
  19: druid::win_handler::InnerAppState<sub_window::HelloState>::do_window_event<sub_window::HelloState>
             at .\druid\src\win_handler.rs:434
  20: druid::win_handler::AppState<sub_window::HelloState>::do_window_event<sub_window::HelloState>
             at .\druid\src\win_handler.rs:583
  21: druid::win_handler::impl$7::mouse_move<sub_window::HelloState>
             at .\druid\src\win_handler.rs:949
  22: druid_shell::backend::windows::window::impl$7::window_proc::closure$12
             at .\druid-shell\src\backend\windows\window.rs:1117
  23: druid_shell::backend::windows::window::impl$6::with_wnd_state::closure$0<druid_shell::backend::windows::window::impl$7::window_proc::closure$12,tuple$<> >
             at .\druid-shell\src\backend\windows\window.rs:504
  24: enum$<core::option::Option<ref_mut$<druid_shell::backend::windows::window::WndState> >, 1, 18446744073709551615, Some>::map<ref_mut$<druid_shell::backend::windows::window::WndState>,tuple$<>,druid_shell::backend::windows::window::impl$6::with_wnd_state::c
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\core\src\option.rs:823
  25: druid_shell::backend::windows::window::MyWndProc::with_wnd_state<druid_shell::backend::windows::window::impl$7::window_proc::closure$12,tuple$<> >
             at .\druid-shell\src\backend\windows\window.rs:504
  26: druid_shell::backend::windows::window::impl$7::window_proc
             at .\druid-shell\src\backend\windows\window.rs:1078
  27: druid_shell::backend::windows::window::win_proc_dispatch
             at .\druid-shell\src\backend\windows\window.rs:1684
  28: CallWindowProcW
  29: DispatchMessageW
  30: druid_shell::backend::windows::application::Application::run
             at .\druid-shell\src\backend\windows\application.rs:161
  31: druid_shell::application::Application::run
             at .\druid-shell\src\application.rs:150
  32: druid::app::AppLauncher<sub_window::HelloState>::launch<sub_window::HelloState>
             at .\druid\src\app.rs:267
  33: sub_window::main
             at .\druid\examples\sub_window.rs:65
  34: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\Users\joshi\Jarvis\rust_target_dir\debug\examples\sub_window.exe` (exit code: 0x80000003)
```

**Pull request merged**
