### PR TITLE
Support selected menu items with GTK backend

### PR DESCRIPTION
**Pull request by CryZe**
This simply constructs a `CheckMenuItem` instead of a `MenuItem` in case the menu item is selected.

### CODE REVIEW

**Comment by jneem** [comment]
Did you push the right commit? I'm not seeing GTK changes...

**Comment by CryZe** [comment]
Yes, there's 2 commits. The second fixes a CI issue.

**Comment by jneem** [comment]
Ah, sorry. For some reason, I managed to get github to only show me the changes of the second commit...

**Comment by jneem** [comment]
Hm, I'm playing around with the multiwin example and the behavior of unselected items is a bit strange: sometimes they show an empty checkbox and sometimes they show nothing. It seems like to match the expected GTK behavior, the druid API will need to use a 3-state enum instead of a bool, right? I mean, GTK distinguishes between: selected (box with a tick), selectable but not selected (empty box), and not selectable (nothing).

**Comment by CryZe** [comment]
Mmh I haven't seen any empty checkboxes, is there a way to consistently reproduce it? Also yeah technically having 3 cases would be ideal.

**Comment by jneem** [comment]
This is what it looks like when I run the multiwin example 

https://user-images.githubusercontent.com/1448113/143067063-98e69a00-63a6-45a7-98e3-5478f1ca1de5.mp4

**Comment by CryZe** [comment]
I believe this just go superseded by: https://github.com/linebender/druid/pull/2251

**Pull request closed without merging**
