### PR TITLE
Add MouseButtons.count()

### PR DESCRIPTION
**Pull request by jjl**

### CODE REVIEW

**Review by derekdreery — APPROVED** [review]
Looks good.

**Comment by jjl** [comment]
Good spot, sorted.

**Comment by derekdreery** [comment]
Ack, now clippy is complaining because the object is `Copy`. Would you change it from `&self` to `self`, then clippy will be happy.

**Comment by jjl** [comment]
Done. Hazards of thinking your chamge is too small to upset clippy...

**Pull request merged**
