### PR TITLE
Show/Hide Window Programmatically

### PR DESCRIPTION
**Pull request by newcomb-luke**
This pull request closes issue  #2089.
You can now hide and show a window programmatically. This is done by a new hide() method on WindowHandle, and by a new command Selector called `HIDE_WINDOW`. This has been implemented on the x11, GTK+, Windows, and macOS backends. Wayland does not yet seem to support hiding/showing windows through their own protocol, and window managers seem to be currently just falling back to the x11 protocol, so Wayland implementation was held off.
`HIDE_WINDOW` leaves the macOS only `HIDE_APPLICATION` Selector alone in that `HIDE_WINDOW` does what it says, and only hides a specific window.
The Window can be shown again by the command `SHOW_WINDOW` which calls the WindowHandle's bring_to_front_and_focus method, which still works as intended when the window is already shown, but when it is hidden, it shows the window again, and brings it to the front and focuses it.

### CODE REVIEW

**Comment by newcomb-luke** [comment]
Seems to still work well with all of the new code changes that have been going on.

**Comment by yim7** [comment]
Thanks, I used your code.

`hide` feature works perfectly, but i can't show window after hiding it.
The deferred_queue cannot be processed because the window does not receive events after hiding. We should call the window display function directly.
And `ShowWindow` don't bring the window into foreground. We can use `SetForegroundWindow` to implement `bring_to_front_and_focus`

**Comment by newcomb-luke** [comment]
> Thanks, I used your code.
> 
> `hide` feature works perfectly, but i can't show window after hiding it. The deferred_queue cannot be processed because the window does not receive events after hiding. We should call the window display function directly. And `ShowWindow` don't bring the window into foreground. We can use `SetForegroundWindow` to implement `bring_to_front_and_focus`

What version of Windows are you trying to run it on? Maybe it is being treated differently. I've tested it on Windows 10.

How did you try to show the window? When I spawn a thread and run `handle.submit_command(druid::commands::SHOW_WINDOW, (), Target::Window(window_id))`, it works perfectly, and shows the window again. The program would crash when I tried to `ShowWindow` in a non-deferred way. 

I will implement `SetForegroundWindow` however, to make it bring the window to the front.

**Comment by newcomb-luke** [comment]
I've added SetForegroundWindow, and everything should be up to date with master.

**Comment by newcomb-luke** [comment]
Synced with master.

**Review by xStrom — APPROVED** [review]
This looks reasonable, thanks for your effort!

**Pull request merged**
