### PR TITLE
Add missing call to `CloseClipboard` on windows

### PR DESCRIPTION
**Pull request by andrewhickman**
This could cause a druid application to steal control of the clipboard, preventing it from working in other apps

### CODE REVIEW

**Review by raphlinus — APPROVED** [review]
Seems good to me. Thanks for catching this!

**Review by ForLoveOfCats — APPROVED** [review]
This explains the oddities I kept seeing with attempting to take screenshots of my app on Windows! I can confirm that this fixes the issue and looks reasonable. This should get an entry under "fixed" in the changelog and then it looks good to me :)

**Comment by ForLoveOfCats** [comment]
Dang it Raph!

**Comment by andrewhickman** [comment]
Just spotted another case where this isn't always called, so don't merge just yet 😄

**Comment by andrewhickman** [comment]
`get_format` wasn't calling `CloseClipboard` in the `None` path, so I've wrapped everything in a little helper function instead

**Review by cmyr — APPROVED** [review]
Thanks!

**Pull request merged**
