### PR TITLE
Fixed spelling of a variable.

### PR DESCRIPTION
**Pull request by MGlolenstine**
Nonbreaking change, just a visual candy.

### CODE REVIEW

**Comment by jneem** [comment]
Thanks for the PR! Unfortunately, our CI is blocked because of an upstream bug, but I'll look after merging this when it's working again.

**Comment by jneem** [comment]
Bah, fixing the CI on master didn't fix it in this PR. Would you mind rebasing?

**Comment by MGlolenstine** [comment]
I'd love to, but I won't be able until Sunday. I'll do it then!

**Comment by MGlolenstine** [comment]
Hmm a tad weird rebase with all other commits.
Should I fix it or is it ok?

Furthermore, sorry for the late fix.

**Comment by Finnerale** [comment]
I think it's best to just create a new PR, this seems a bit chaotic 😄

**Comment by MGlolenstine** [comment]
> I think it's best to just create a new PR, this seems a bit chaotic smile

I agree :smile:

**Pull request closed without merging**
