### PR TITLE
Add example to ViewSwitcher

### PR DESCRIPTION
**Pull request by arifd**
Let me know if you don't like it, I should modify anything? I'm hoping to add examples to many more areas of Druid that could benefit from them.

### CODE REVIEW

**Comment by jneem** [comment]
Did you reach a conclusion about this? FWIW, I don't think it's necessary to have a `main`, because if you repeat that for every example, it's a lot of boilerplate...

**Comment by arifd** [comment]
There has been no feedback to date. And so it's kind of stuck.

**Comment by jneem** [comment]
Well in that case I suggest we just merge it. Having an example is clearly better than not having one, so there's no point in being stuck on it. Any objections?

**Review by jneem — APPROVED** [review]

**Comment by Maan2003** [comment]
the example should be in top level docs of `ViewSwitcher` not `ViewSwitcher::new`?

**Comment by arifd** [comment]
Good question. I wanted it in `new()` because that's when I need to be
reminded of the order of the parameters in the closures.

**Comment by Maan2003** [comment]
Merging, as no objections

**Pull request merged**
