### PR TITLE
Support individual corner radii for kurbo::RoundedRect

### PR DESCRIPTION
**Pull request by SecondFlight**
Depends on [kurbo#166](https://github.com/linebender/kurbo/pull/166) and [piet#391](https://github.com/linebender/piet/pull/391). This PR should not be merged until the upstream crates are updated and this PR is pointed to them. The changes in Kurbo are (mostly) backwards-compatible, so very little needs to change in Druid to incorporate the upstream changes.

image

### CODE REVIEW

**Comment by cmyr** [comment]
@SecondFlight this should now be mergeable?

**Comment by SecondFlight** [comment]
Yeah, I just need to fix merge conflicts and do a smoke test.

**Comment by SecondFlight** [comment]
Did I accidentally float these changes into Druid in another PR?? The change set no longer includes the changes needed for this PR, but the code works and so I think the changes are somehow already on master.

**Comment by SecondFlight** [comment]
Ah nevermind, they were added [here](https://github.com/linebender/druid/commit/d0963674177d338ecbe176f5c2d958d2a2afcbfa) which makes total sense. I'll mark this ready for review, but there's not much to review; the only thing left relating to the rounded rect change is the updated changelog. I made a `.gitignore` change that I stand by as it brings this repo in line with piet and ignores a few thousand files that the rust language server is generating.

**Review by cmyr — APPROVED** [review]
Ah right, I needed to impl this in order for the existing code to compile. 😁

**Pull request merged**
