### PR TITLE
Fix build error on Mac when spin_no_std is enabled by dependents of lazy_static. (#2211)

### PR DESCRIPTION
**Pull request by Steve-xmh**
Fix build error on Mac when spin_no_std is enabled by dependents of lazy_static. (#2211)

### CODE REVIEW

**Comment by xStrom** [comment]
Thanks! We may end up going with this solution, or we may switch out `lazy_static` for `once_cell` as briefly discussed in #2211. I will look into this myself soon.

**Comment by Steve-xmh** [comment]
> Thanks! We may end up going with this solution, or we may switch out `lazy_static` for `once_cell` as briefly discussed in #2211. I will look into this myself soon.

That's ok, take your own time!

Anyway, switch to `once_cell` can be a good choice too. But we can merge it first if just need to temporarily fix this problem.

**Comment by xStrom** [comment]
I think clippy will fail, as I'm still working on that PR myself. I'll run the tests to see.

**Comment by xStrom** [comment]
Okay, `master` now has clippy issues solved thanks to #2215. You can rebase this on `master` and then the tests should succeed.

**Comment by Steve-xmh** [comment]
Already merged.

**Review by xStrom — APPROVED** [review]
Thanks! This does resolve the issue, so I'll approve this as the quick fix to have a working `master`.

Later we might switch out `lazy_static` completely, but that will be a separate PR.

**Pull request merged**
