### PR TITLE
Parameterize Container, SizedBox and Align on child type

### PR DESCRIPTION
**Pull request by PoignardAzur**
Add get_child method to all three types.

### CODE REVIEW

**Comment by PoignardAzur** [comment]
Again, I'm not sure about this, discussion is welcome.

In particular, I have doubts about the semantics of [the `id()` method](https://github.com/linebender/druid/pull/1937/files#diff-ceed7bf9f161414c171139ac49a3e40c874757df2a869a48e97dcbee4c3550d8R205-R207), but I rewrote it as best as I could.

**Review by cmyr — APPROVED** [review]
Looks good, modulo the broken test. :)

**Comment by PoignardAzur** [comment]
I'm still getting these test failures:

```
---- tests::layout_tests::flex_paint_rect_overflow stdout ----
thread 'tests::layout_tests::flex_paint_rect_overflow' panicked at 'assertion failed: `(left == right)`
  left: `(10.0, 10.0)`,
 right: `(-10.0, -10.0)`', druid/src/tests/layout_tests.rs:181:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::layout_tests::simple_paint_rect stdout ----
thread 'tests::layout_tests::simple_paint_rect' panicked at 'assertion failed: `(left == right)`
  left: `(10.0, 10.0)`,
 right: `(10.0, -10.0)`', druid/src/tests/layout_tests.rs:108:9
```

The thing is, I'm not even sure whether I should even fix them, or just change the values in the test.

Best I can tell, these failures are due to me changing the way `SizedBox` stores its child, as a `WidgetPod` instead of a `Box<dyn Widget>`. But I'm not sure the values are wrong? I'm not sure what referential they're meant to be in, for starters. I'm going to try running examples to check what happens.

**Comment by PoignardAzur** [comment]
I'm also getting `missed call to set_origin` warnings. Uuugh.

I'm closing this for now. I don't want to bother.

**Pull request closed without merging**
