### PR TITLE
Added strikethrough

### PR DESCRIPTION
**Pull request by jenra-uwu**
This pull request adds strikethrough to druid and updates the markdown example to use `~~this syntax~~` for ~~strikethrough~~.

### CODE REVIEW

**Review by Maan2003 — APPROVED** [review]
Thanks!

**Comment by jenra-uwu** [comment]
> Thanks! Probably a good idea to add this to example as well.

Which example is that?

**Comment by Maan2003** [comment]
markdown_preview.rs

**Comment by cmyr** [comment]
Worth noting that I think this may only work on certain platforms, maybe even only linux? I don't recall exactly the state of this in piet.

**Comment by jenra-uwu** [comment]
> Worth noting that I think this may only work on certain platforms, maybe even only linux? I don't recall exactly the state of this in piet.

Oh no. I have no way to test it on Windows/macOS and don't know how to test it on the web. I may send a pull request for piet if thats the case, since I really want strikethrough for my matrix client. Any idea how I can start tackling this?

**Comment by cmyr** [comment]
Here's the tracking issue, without much info. It may be that this is now only missing on mac? in any case I'll post some more info here: https://github.com/linebender/piet/issues/301

**Comment by jneem** [comment]
This can be merged, right?

**Comment by jneem** [comment]
I'm going to take that as a "yes"

**Pull request merged**
