### PR TITLE
Add default horizontal & vertical padding to theme

### PR DESCRIPTION
**Pull request by cmyr**
This also uses these values in the Flex container, via new
add_default_spacer and with_default_spacer methods. This should
be the preferred way of spacing the standard control widgets.

This is progress on #1216; I also want to go and remove any other
internal padding constants from existing widgets.

### CODE REVIEW

**Review by Finnerale — APPROVED** [review]
Seems like a good idea.

Maybe `with_theme_spacer` would be a more obvious name? Because I have no concept of a "default spacer" but I would immediately know what's meant by a "theme spacer".

**Comment by cmyr** [comment]
I was thinking about making this `with_spacer` and making `with_spacer` be `with_fixed_spacer`, but that would be annoying breakage. maybe `with_auto_spacer`?

**Comment by Finnerale** [comment]
Hmm, I've the same problem with `with_auto_spacer` as with `with_default_spacer`, actually I've even more of an issue with 'auto' because it makes me think of something adaptive...

Actually, now that I think about it again, `with_default_spacer` seems fine to me. Calling it `with_theme_spacer` makes no sense if the user (or even Druid) would define multiple different "default" sizes.

Maybe we could call them `with_spacer` and `with_custom_spacer`?. I don't think changing `with_spacer` would be an issue, as it is a single find-and-replace to fix it.

This is one of the rather rare moments where I wish Rust had overloading...

**Comment by cmyr** [comment]
I'm not sure there's anything I like better than `with_default_spacer`, so I think I'm just going to keep that as-is for now 🤷

**Pull request merged**
