### PR TITLE
Make TextBox placeholder translatable

### PR DESCRIPTION
**Pull request by Swatinem**
This makes the `TextBox` placeholder a `LabelText` which can be initialized with a `LocalizedString` and thus translated.

The problem that I have is that the `TextBox` seems to be bound to a very specific editable text via `lens`, and that couples the `LabelText` to the same Data, which means I currently can’t use anything else from my main Data as placeholders of the `LocalizedString` (or `Dynamic` for that matter).

### CODE REVIEW

**Review by Maan2003 — APPROVED** [review]
Looks good to me. Thanks!

**Comment by Maan2003** [comment]
> The problem that I have is that the TextBox seems to be bound to a very specific editable text via lens, and that couples the LabelText to the same Data, which means I currently can’t use anything else from my main Data as placeholders of the LocalizedString (or Dynamic for that matter).

that is a limitation of Lens. I don't think it is easily to fix

**Comment by Swatinem** [comment]
I noted down the limitations in the commit message, otherwise the code is unchanged and was just rebased on master.

**Comment by jneem** [comment]
This is good to go, right?

**Comment by Swatinem** [comment]
@jneem yes, this should be good to go

**Pull request merged**
