### PR TITLE
Update nix to 0.24.0

### PR DESCRIPTION
**Pull request by Maan2003**
#2208 revived

### CODE REVIEW

**Review by cmyr — APPROVED** [review]
Thanks!

**Comment by CryZe** [comment]
What about reducing the feature set?

**Comment by cmyr** [comment]
@CryZe can you elaborate?

**Comment by CryZe** [comment]
nix 0.24 introduces lots of features. They are enabled by default, but you probably want to actually make use of this and reduce it to only what is actually used.

**Pull request merged**
