### PR TITLE
derive Widget proposal

### PR DESCRIPTION
**Pull request by sysint64**
This PR adds derive macro to implement the Widget trait. It can be helpful for a composite widget that is built from existing widgets.

**Example**

```rust
#[derive(Widget)]
pub struct TextBoxWithLabel {
    #[widget(meta)]
    meta: CompositeMeta<String>,
    label: String,
}

impl TextBoxWithLabel {
    fn new(label: impl Into<String>) -> Self {
        TextBoxWithLabel {
            meta: CompositeMeta::default(),
            label: label.into(),
        }
    }

    fn build(&self) -> impl Widget<String> + 'static {
        Flex::column()
            .cross_axis_alignment(CrossAxisAlignment::Start)
            .with_child(Label::new(self.label.clone()))
            .with_spacer(4.)
            .with_child(TextBox::new().with_placeholder(String::from("Test")))
    }
}

fn make_ui() -> impl Widget<String> {
    Align::centered(
        Flex::column()
            .with_child(TextBoxWithLabel::new("My text box"))
            .padding(10.0),
    )
}
```

this will expand to this:

```rust
mod text_box_with_label_derived_widgets {
    use super::*;
    use druid::kurbo::{Point, Rect, Size};
    use druid::{
        BoxConstraints, Data, Env, Event, EventCtx, LayoutCtx, LifeCycle, LifeCycleCtx, PaintCtx,
        UpdateCtx, Widget, WidgetPod,
    };
    impl Widget<String> for TextBoxWithLabel {
        fn event(&mut self, ctx: &mut EventCtx, event: &Event, data: &mut String, env: &Env) {
            if let Some(widget) = &mut self.meta.widget {
                widget.event(ctx, event, data, env);
            }
        }
        fn lifecycle(
            &mut self,
            ctx: &mut LifeCycleCtx,
            event: &LifeCycle,
            data: &String,
            env: &Env,
        ) {
            if let LifeCycle::WidgetAdded = event {
                self.meta
                    .widget
                    .replace(WidgetPod::new(self.build()).boxed());
            }
            if let Some(widget) = &mut self.meta.widget {
                widget.lifecycle(ctx, event, data, env);
            }
        }
        fn update(&mut self, ctx: &mut UpdateCtx, _: &String, data: &String, env: &Env) {
            if let Some(widget) = &mut self.meta.widget {
                widget.update(ctx, data, env);
            }
        }
        fn layout(
            &mut self,
            ctx: &mut LayoutCtx,
            bc: &BoxConstraints,
            data: &String,
            env: &Env,
        ) -> Size {
            match &mut self.meta.widget {
                Some(widget) => {
                    let size = widget.layout(ctx, &bc, data, env);
                    let rect = Rect::from_origin_size(Point::ORIGIN, size);
                    widget.set_layout_rect(ctx, data, env, rect);
                    size
                }
                None => Size::ZERO,
            }
        }
        fn paint(&mut self, ctx: &mut PaintCtx, data: &String, env: &Env) {
            if let Some(widget) = &mut self.meta.widget {
                widget.paint(ctx, data, env);
            }
        }
    }
}
pub use text_box_with_label_derived_widgets::*;
```

### CODE REVIEW

**Comment by sysint64** [comment]
this is my previous implementation for composite widgets: https://github.com/linebender/druid/pull/1247/commits/7df9f11a83f8d566419ed0a86deaef2e38663458

but it requires to wrap `TextBoxWithLabel` into `CompositeWidget`:

```rust
pub struct TextBoxWithLabel {
    label: String,
}

impl TextBoxWithLabel {
    fn new(label: impl Into<String>) -> Self {
        TextBoxWithLabel {
            label: label.into(),
        }
    }
}

impl CompositeBuild<String, Flex<String>> for TextBoxWithLabel {
    fn build(&self) -> Flex<String> {
        Flex::column()
            .cross_axis_alignment(CrossAxisAlignment::Start)
            .with_child(Label::new(self.label.clone()))
            .with_spacer(4.)
            .with_child(TextBox::new().with_placeholder(String::from("Test")))
    }
}

fn make_ui() -> impl Widget<String> {
    Align::centered(
        Flex::column()
            .with_child(CompositeWidget::new(TextBoxWithLabel::new("My text box")))
            .padding(10.0),
    )
}
```

**Comment by derekdreery** [comment]
So this derive would be competing with

```rust
fn make_complex_widget(label: &str) -> impl Widget<String> {
  Flex::column()
    .cross_axis_alignment(CrossAxisAlignment::Start)
    .with_child(Label::new(label.clone()))
    .with_spacer(4.)
    .with_child(TextBox::new().with_placeholder(String::from("Test")))  
}
```

or a more complex example

```rust
#[derive(Data, Lens)]
struct MyData {
  name: String,
  age: u16
}

fn make_complex_widget(label: &str) -> impl Widget<MyData> {
  Flex::column()
    .cross_axis_alignment(CrossAxisAlignment::Start)
    .with_child(Label::new(label.clone()))
    .with_spacer(4.)
    .with_child(TextBox::new().with_placeholder(String::from("Test")).lens(MyData::name))
    .with_spacer(4.)
    .with_child(TextBox::new().with_placeholder(String::from("Test")).lens(MyData::age))
}
```

**Comment by sysint64** [comment]
@derekdreery yes I agree, this proposal aims to solve a little bit different problem, in my case I would like to create UI kit from already existed widgets, and that widgets should be able to have some builder method like in the `Texbox.with_placeholder`, or `Flex.with_child`. Some simple example I have in my project:
```rust
fn build_command_input() -> impl Widget<DebugState> {
    AccessorDecorator::new(
        TerminalTextboxDecorator::new(),
        Focus::new(
            EditableText::new()
                .with_placeholder("Enter the command")
                .lens(DebugState::terminal_command),
        )
        .with_auto_focus(true)
        .with_id(TERMINAL_WIDGET_ID),
    )
    .padding(2.0)
}
```

I would like to create from this full-fledged widget that will contain `.with_auto_focus`, `.with_placeholder` methods, and so on.

**Comment by rjwittams** [comment]
Why does this need to be a macro? It seems like it could just be a wrapper around trait with a build function.
I think I'm missing what it does with the fields that aren't meta.

**Comment by cmyr** [comment]
I want to say that I see the motivation for this, and it feels like actually a similar motivation to crochet; it is trying to fix the problem that druid is not truly declarative, and that at various times you need to mutate widgets but maybe don't have access to the concrete widget because it is hidden behind a `WidgetPod` or has been `Box`ed or something similar.

I've run into similar things myself, and have experimented with various ways of solving it, although none of them have felt particularly great. The main problem is that we don't have a tree of widgets and we don't do diffing, so if we're *actually* rebuilding the graph on each `update`, that will get expensive.

I'm not sure I see what this particular version buys us, though? It feels like a lot of what this would be used for could be achieved with a `Controller` widget?

**Comment by sysint64** [comment]
> Why does this need to be a macro? It seems like it could just be a wrapper around trait with a build function.
I think I'm missing what it does with the fields that aren't meta.

The first version was a wrapper: [example](https://github.com/linebender/druid/blob/7df9f11a83f8d566419ed0a86deaef2e38663458/druid/examples/composite.rs).

But I don't like, that I can't just put struct `TextBoxWithLabel` into the flex, this is how API looks with wrapper:
`.with_child(CompositeWidget::new(TextBoxWithLabel::new("My text box")))`

> I'm not sure I see what this particular version buys us, though? It feels like a lot of what this would be used for could be achieved with a Controller widget?

The main idea is simply to create a widget from other widgets, it's similar to a function-based widget, but struct can hold some state and be a builder-like widget. Back to my previous example with `build_command_input` - I could extract it to another widget and create a UI kit like this:

```rust
#[derive(Widget)]
pub struct TerminalTextBox {
    #[widget(meta)]
    meta: CompositeMeta<String>,
    placeholder: String,
    autofocus: bool,
}

impl TextBoxWithLabel {
    fn new() -> Self {
        TextBoxWithLabel {
            meta: CompositeMeta::default(),
            placeholder: String::new(),
            autofocus: false,
        }
    }

   pub fn with_placeholder(mut self, placeholder: impl Into<String>) -> Self {
        self.placeholder = placeholder.into();
        self
    }

   pub fn with_autofocus(mut self, autofocus: bool) -> Self {
        self.autofocus = autofocus;
        self
    }

    fn build(&self) -> impl Widget<String> + 'static {
        AccessorDecorator::new(
            TerminalTextboxDecorator::new(),
            Focus::new(
                EditableText::new()
                    .with_placeholder(self.placeholder)
            )
            .with_auto_focus(self.autofocus)
        )
        .padding(2.0)
    }
}
```

and use this like this:

```rust
fn build_command_input() -> impl Widget<DebugState> {
    TerminalTextBox::new()
        .with_placeholder("Enter the command")
        .with_auto_focus(true)
        .with_id(TERMINAL_WIDGET_ID)
        .lens(DebugState::terminal_command)
}
```

Also, it can be useful for built-in widgets, there is an example - my try to add the `Focus` widget, instead of creating an additional controller to manage focus inside the `TextBox` widget we could just rewrite it to something like this:

```rust
#[derive(Widget)]
pub struct TextBox {
    #[widget(meta)]
    meta: CompositeMeta<String>,
    placeholder: String,
    autofocus: bool,
}

impl TextBoxWithLabel {
    fn new() -> Self {
        TextBoxWithLabel {
            meta: CompositeMeta::default(),
            placeholder: String::new(),
            autofocus: false,
        }
    }

   pub fn with_placeholder(mut self, placeholder: impl Into<String>) -> Self {
        self.placeholder = placeholder.into();
        self
    }

   pub fn with_autofocus(mut self, autofocus: bool) -> Self {
        self.autofocus = autofocus;
        self
    }

    fn build(&self) -> impl Widget<String> + 'static {
        Focus::new(
            TextBoxImpl::new()
                .with_placeholder(self.placeholder)
        )
        .with_auto_focus(self.autofocus)
    }
}
```

i.e., wrap it to the `Focus` widget.

**Comment by rjwittams** [comment]
.with_child(CompositeWidget::new(TextBoxWithLabel::new("My text box")))

This could be sugared to:

.with_child(TextBoxWithLabel::new("My text box").as_widget())

With a CompositeExt trait.

It’s possible that the arguments to some of the methods that take widgets E.g with_child could be something more flexible, E.g Into, to allow automatic wrapping. I haven’t tried this, and it could come at a later stage.

**Comment by cmyr** [comment]
I think we're ultimately not going to go to `derive` here; the medium/long-term solution to this problem will likely be something like crochet.

Going to close this; if there's more discussion to have feel free to reopen!

**Pull request closed without merging**
