### PR TITLE
Add Checkbox::set_text function.

### PR DESCRIPTION
**Pull request by Finnerale**
I need this to port `Checkbox` to Crochet and it seems useful enough to go into Druid directly.

### CODE REVIEW

**Comment by ForLoveOfCats** [comment]
Would the usage case in Crotchet still be covered by this if it was a builder fn `with_label` or a constructor `from_label` like is on `Button`?

**Comment by ForLoveOfCats** [comment]
Ah nevermind, I see that this is about updating the text value

**Comment by Finnerale** [comment]
@ForLoveOfCats ~No, it wouldn't. I want to change the label without having to recreate the widget.~ You noticed that already

On adding setters in general to Druid:

I believe Druid would benefit from such functionality. Recreating widgets to change their properties mostly works for widgets without internal state, but even those then require being properly reinitialized with `WidgetAdded`and so forth. And for widgets with internal state, recreating them will even cause user-visible problems. And if we add setters to those widgets, it would seem inconsistent not to have them on cheap-to-recreate widgets.

**Comment by ForLoveOfCats** [comment]
I agree that mutating widgets in-tree is a reasonable thing to be doing.

As this is not actually being passed a `Label` widget but instead the `LabelText` perhaps it would be more accurately called `set_label_text` or `set_text`? Otherwise this looks good to me now that I've actually looked at the usage case.

**Comment by Finnerale** [comment]
@ForLoveOfCats Sounds good! I renamed it to `set_text` and also updated the doc comments.

**Comment by ForLoveOfCats** [comment]
Missed the changelog but then it looks good to me :+1:

**Comment by Finnerale** [comment]
Oops, now it should be right!

**Review by ForLoveOfCats — APPROVED** [review]

**Pull request merged**
