### PR TITLE
const generics for Data :)

### PR DESCRIPTION
**Pull request by derekdreery**
We can't land this for now - we need `min_const_generics` which will ship in march.

### CODE REVIEW

**Comment by Maan2003** [comment]
The time has come :partying_face:. I can't find a button to rerun workflows.

**Comment by derekdreery** [comment]
I will do a dummy commit to re-trigger.

**Comment by cmyr** [comment]
this will need a rebase, as well.

**Comment by derekdreery** [comment]
Rebased :)

**Review by cmyr — APPROVED** [review]
The future we were all promised has finally arrived.

**Comment by derekdreery** [comment]
Future now

**Pull request merged**
