### PR TITLE
Satisfy clippy 1.62

### PR DESCRIPTION
**Pull request by xStrom**
Lints addressed:
* [`format_push_string`](https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string)
* [`let_unit_value`](https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value)

### CODE REVIEW

**Review by jneem — APPROVED** [review]

**Comment by xStrom** [comment]
Looks like some pseudocode in GTK backend comments is failing, will need to look into that a bit more.

**Comment by jneem** [comment]
Those doc comments have been there since forever. Strange that `rustdoc` only just decided to try compiling them...

**Comment by xStrom** [comment]
I don't know for sure, but this line in the changelog might explain it:

`cargo test` now passes `--target` to `rustdoc` if the specified target is the same as the host target. [#10594](https://github.com/rust-lang/cargo/pull/10594)

**Comment by xStrom** [comment]
The tests require the code to be full, even if most of it is hidden. Given that it is only one macro's docs, I'll just set the ignore tag for it.

**Pull request merged**
