### PR TITLE
Wayland output reinitialization

### PR DESCRIPTION
**Pull request by james-lawrence**
- wayland dependency updates, because why not.
- basic support for display reinitialization (hibernation/sleep/monitor power off recovery)

### CODE REVIEW

**Comment by james-lawrence** [comment]
once this is in I have partial clipboard (paste) support and repeating keys ready to go.

**Comment by jplatte** [comment]
I didn't know there was already work being done on a native wayland backend for druid. Thanks you for that! :heart:

**Review by Maan2003 — APPROVED** [review]
Thanks!

**Comment by james-lawrence** [comment]
@jplatte np, but seems like i'll only get druid to around 80%, functional but with some rough edges. I plan on stopping in the new year to start working on other projects. mostly just cleaning up and upstreaming my fork where applicable in the hopes the community takes it the rest of the way.

but most of that work will just be integrating with the druid apis (Modals/Dialogs/Context menus).

**Comment by james-lawrence** [comment]
@Maan2003 sorry to bump, but can we merge? just to keep moving these things along. have like 5 more PRs coming ;)

**Comment by Maan2003** [comment]
Sure. Also, Thanks for all the wayland work!

**Comment by james-lawrence** [comment]
np, thank you guys for maintaining the base UI toolkit to work off of. ;)

**Pull request merged**
