### PR TITLE
Implement request_close() support for Windows in druid-shell

### PR DESCRIPTION
**Pull request by tay64**
This PR implements the Windows part of [#1159 "Implement close request interception"](https://github.com/linebender/druid/issues/1159).

----

This is my first PR for this project; hope my submitting a PR without an introduction or any warning is OK?
I've just encountered the non-working CLOSE_WINDOW while working on an app I'm building as an exercise to grok the Rust way, and fixing it seemed straightforward.
Hope it can be of use.

### CODE REVIEW

**Comment by jneem** [comment]
Thanks for the patch! Can you add it to the changelog also? Look for the line containing #1118

**Comment by tay64** [comment]
done!

**Comment by tay64** [comment]
(updated from master)

**Review by jneem — APPROVED** [review]
Thanks! I just want to find a minute to give it a quick spin on windows, and then I'll merge.

**Comment by tay64** [comment]
Thank you!

**Pull request merged**
